import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/donation_provider.dart';
import '../../models/food_donation.dart';
import '../../widgets/custom_text_field.dart';
import '../../widgets/loading_overlay.dart';

class CreateDonationScreen extends StatefulWidget {
  const CreateDonationScreen({Key? key}) : super(key: key);

  @override
  State<CreateDonationScreen> createState() => _CreateDonationScreenState();
}

class _CreateDonationScreenState extends State<CreateDonationScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _quantityController = TextEditingController();
  final _unitController = TextEditingController(text: 'servings');
  final _allergenController = TextEditingController();
  final _instructionsController = TextEditingController();
  final _pickupAddressController = TextEditingController();
  final _contactPhoneController = TextEditingController();
  final _estimatedMealsController = TextEditingController();
  final _estimatedPeopleController = TextEditingController();
  
  List<FoodType> _selectedFoodTypes = [];
  DateTime _preparedAt = DateTime.now();
  DateTime _expiresAt = DateTime.now().add(const Duration(hours: 4));
  DateTime _availableFrom = DateTime.now();
  DateTime _availableUntil = DateTime.now().add(const Duration(hours: 12));
  FoodSafetyLevel _safetyLevel = FoodSafetyLevel.high;
  bool _requiresRefrigeration = false;
  bool _isVegetarian = false;
  bool _isVegan = false;
  bool _isHalal = false;
  bool _isUrgent = false;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _quantityController.dispose();
    _unitController.dispose();
    _allergenController.dispose();
    _instructionsController.dispose();
    _pickupAddressController.dispose();
    _contactPhoneController.dispose();
    _estimatedMealsController.dispose();
    _estimatedPeopleController.dispose();
    super.dispose();
  }

  Future<void> _createDonation() async {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedFoodTypes.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select at least one food type'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final donationProvider = Provider.of<DonationProvider>(context, listen: false);
    
    final userId = authProvider.appUser?.uid;
    if (userId == null) return;

    final donation = FoodDonation(
      id: '', // Will be generated by service
      donorId: userId,
      title: _titleController.text.trim(),
      description: _descriptionController.text.trim(),
      foodTypes: _selectedFoodTypes,
      quantity: int.parse(_quantityController.text.trim()),
      unit: _unitController.text.trim(),
      preparedAt: _preparedAt,
      expiresAt: _expiresAt,
      availableFrom: _availableFrom,
      availableUntil: _availableUntil,
      safetyLevel: _safetyLevel,
      requiresRefrigeration: _requiresRefrigeration,
      isVegetarian: _isVegetarian,
      isVegan: _isVegan,
      isHalal: _isHalal,
      allergenInfo: _allergenController.text.trim().isEmpty ? null : _allergenController.text.trim(),
      specialInstructions: _instructionsController.text.trim().isEmpty ? null : _instructionsController.text.trim(),
      images: [],
      pickupLocation: {},
      pickupAddress: _pickupAddressController.text.trim(),
      donorContactPhone: _contactPhoneController.text.trim(),
      status: DonationStatus.listed,
      estimatedMeals: _estimatedMealsController.text.trim().isEmpty ? 0 : int.parse(_estimatedMealsController.text.trim()),
      estimatedPeopleServed: _estimatedPeopleController.text.trim().isEmpty ? 0 : int.parse(_estimatedPeopleController.text.trim()),
      createdAt: DateTime.now(),
      isUrgent: _isUrgent,
    );

    final donationId = await donationProvider.createDonation(donation);

    if (donationId != null && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Donation created successfully!'),
          backgroundColor: Colors.green,
        ),
      );
      Navigator.pop(context, true); // Return true to indicate success
    } else if (mounted && donationProvider.errorMessage != null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(donationProvider.errorMessage!),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Donation'),
        backgroundColor: Theme.of(context).colorScheme.primary,
        foregroundColor: Colors.white,
      ),
      body: Consumer<DonationProvider>(
        builder: (context, donationProvider, child) {
          return LoadingOverlay(
            isLoading: donationProvider.isLoading,
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    // Basic Information
                    Text(
                      'Basic Information',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    CustomTextField(
                      controller: _titleController,
                      label: 'Donation Title',
                      hintText: 'e.g., Fresh Sandwiches from Lunch Event',
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter a title';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    CustomTextField(
                      controller: _descriptionController,
                      label: 'Description',
                      hintText: 'Describe the food items in detail',
                      maxLines: 3,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter a description';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    Row(
                      children: [
                        Expanded(
                          child: CustomTextField(
                            controller: _quantityController,
                            label: 'Quantity',
                            keyboardType: TextInputType.number,
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Required';
                              }
                              if (int.tryParse(value) == null) {
                                return 'Invalid number';
                              }
                              return null;
                            },
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: CustomTextField(
                            controller: _unitController,
                            label: 'Unit',
                            hintText: 'servings, kg, packages',
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Required';
                              }
                              return null;
                            },
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),

                    // Estimated Impact
                    Row(
                      children: [
                        Expanded(
                          child: CustomTextField(
                            controller: _estimatedMealsController,
                            label: 'Estimated Meals',
                            keyboardType: TextInputType.number,
                            hintText: 'Approx. meals',
                            validator: (value) {
                              if (value != null && value.isNotEmpty && int.tryParse(value) == null) {
                                return 'Invalid number';
                              }
                              return null;
                            },
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: CustomTextField(
                            controller: _estimatedPeopleController,
                            label: 'People Served',
                            keyboardType: TextInputType.number,
                            hintText: 'Approx. people',
                            validator: (value) {
                              if (value != null && value.isNotEmpty && int.tryParse(value) == null) {
                                return 'Invalid number';
                              }
                              return null;
                            },
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),

                    // Food Types
                    Text(
                      'Food Types',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),
                    
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: FoodType.values.map((type) {
                        final isSelected = _selectedFoodTypes.contains(type);
                        return FilterChip(
                          label: Text(_getFoodTypeDisplayName(type)),
                          selected: isSelected,
                          onSelected: (selected) {
                            setState(() {
                              if (selected) {
                                _selectedFoodTypes.add(type);
                              } else {
                                _selectedFoodTypes.remove(type);
                              }
                            });
                          },
                        );
                      }).toList(),
                    ),
                    const SizedBox(height: 24),

                    // Dietary Information
                    Text(
                      'Dietary Information',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    CheckboxListTile(
                      title: const Text('Vegetarian'),
                      value: _isVegetarian,
                      onChanged: (value) {
                        setState(() {
                          _isVegetarian = value ?? false;
                        });
                      },
                    ),
                    CheckboxListTile(
                      title: const Text('Vegan'),
                      value: _isVegan,
                      onChanged: (value) {
                        setState(() {
                          _isVegan = value ?? false;
                          if (_isVegan) _isVegetarian = true;
                        });
                      },
                    ),
                    CheckboxListTile(
                      title: const Text('Halal'),
                      value: _isHalal,
                      onChanged: (value) {
                        setState(() {
                          _isHalal = value ?? false;
                        });
                      },
                    ),
                    const SizedBox(height: 16),

                    CustomTextField(
                      controller: _allergenController,
                      label: 'Allergen Information (Optional)',
                      hintText: 'e.g., Contains nuts, dairy',
                      maxLines: 2,
                    ),
                    const SizedBox(height: 24),

                    // Safety & Storage
                    Text(
                      'Safety & Storage',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    DropdownButtonFormField<FoodSafetyLevel>(
                      value: _safetyLevel,
                      decoration: const InputDecoration(
                        labelText: 'Food Safety Level',
                      ),
                      items: FoodSafetyLevel.values.map((level) {
                        return DropdownMenuItem(
                          value: level,
                          child: Text(_getSafetyLevelDisplayName(level)),
                        );
                      }).toList(),
                      onChanged: (value) {
                        if (value != null) {
                          setState(() {
                            _safetyLevel = value;
                          });
                        }
                      },
                    ),
                    const SizedBox(height: 16),

                    CheckboxListTile(
                      title: const Text('Requires Refrigeration'),
                      subtitle: const Text('Food needs to be kept cold'),
                      value: _requiresRefrigeration,
                      onChanged: (value) {
                        setState(() {
                          _requiresRefrigeration = value ?? false;
                        });
                      },
                    ),

                    CheckboxListTile(
                      title: const Text('Urgent Donation'),
                      subtitle: const Text('Expires very soon'),
                      value: _isUrgent,
                      onChanged: (value) {
                        setState(() {
                          _isUrgent = value ?? false;
                        });
                      },
                    ),
                    const SizedBox(height: 24),

                    // Time Information
                    Text(
                      'Time Information',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    _buildDateTimePicker(
                      'Prepared At',
                      _preparedAt,
                      (date) => setState(() => _preparedAt = date),
                    ),
                    const SizedBox(height: 16),

                    _buildDateTimePicker(
                      'Expires At',
                      _expiresAt,
                      (date) => setState(() => _expiresAt = date),
                    ),
                    const SizedBox(height: 16),

                    _buildDateTimePicker(
                      'Available From',
                      _availableFrom,
                      (date) => setState(() => _availableFrom = date),
                    ),
                    const SizedBox(height: 16),

                    _buildDateTimePicker(
                      'Available Until',
                      _availableUntil,
                      (date) => setState(() => _availableUntil = date),
                    ),
                    const SizedBox(height: 24),

                    // Pickup Information
                    Text(
                      'Pickup Information',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),

                    CustomTextField(
                      controller: _pickupAddressController,
                      label: 'Pickup Address',
                      hintText: 'Full address where food can be picked up',
                      maxLines: 2,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter pickup address';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    CustomTextField(
                      controller: _contactPhoneController,
                      label: 'Contact Phone',
                      keyboardType: TextInputType.phone,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter contact phone';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),

                    CustomTextField(
                      controller: _instructionsController,
                      label: 'Special Instructions (Optional)',
                      hintText: 'e.g., Ring the back door bell',
                      maxLines: 2,
                    ),
                    const SizedBox(height: 32),

                    // Submit Button
                    ElevatedButton(
                      onPressed: _createDonation,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Theme.of(context).colorScheme.primary,
                        foregroundColor: Colors.white,
                      ),
                      child: const Text('Create Donation'),
                    ),
                    const SizedBox(height: 16),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildDateTimePicker(String label, DateTime value, Function(DateTime) onChanged) {
    return InkWell(
      onTap: () async {
        final date = await showDatePicker(
          context: context,
          initialDate: value,
          firstDate: DateTime.now().subtract(const Duration(days: 1)),
          lastDate: DateTime.now().add(const Duration(days: 30)),
        );

        if (date != null) {
          final time = await showTimePicker(
            context: context,
            initialTime: TimeOfDay.fromDateTime(value),
          );

          if (time != null) {
            onChanged(DateTime(
              date.year,
              date.month,
              date.day,
              time.hour,
              time.minute,
            ));
          }
        }
      },
      child: InputDecorator(
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
          suffixIcon: const Icon(Icons.calendar_today),
        ),
        child: Text(
          '${value.day}/${value.month}/${value.year} ${value.hour}:${value.minute.toString().padLeft(2, '0')}',
        ),
      ),
    );
  }

  String _getFoodTypeDisplayName(FoodType type) {
    switch (type) {
      case FoodType.cooked:
        return 'Cooked';
      case FoodType.raw:
        return 'Raw';
      case FoodType.packaged:
        return 'Packaged';
      case FoodType.dairy:
        return 'Dairy';
      case FoodType.fruits:
        return 'Fruits';
      case FoodType.vegetables:
        return 'Vegetables';
      case FoodType.grains:
        return 'Grains';
      case FoodType.meat:
        return 'Meat';
      case FoodType.seafood:
        return 'Seafood';
      case FoodType.bakery:
        return 'Bakery';
      case FoodType.beverages:
        return 'Beverages';
      case FoodType.other:
        return 'Other';
    }
  }

  String _getSafetyLevelDisplayName(FoodSafetyLevel level) {
    switch (level) {
      case FoodSafetyLevel.high:
        return 'High - Properly stored and handled';
      case FoodSafetyLevel.medium:
        return 'Medium - Standard handling';
      case FoodSafetyLevel.low:
        return 'Low - Basic handling';
    }
  }
}